# Generated by Django 3.2.9 on 2021-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
