# Generated by Django 3.2.9 on 2021-12-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='feed.Profile'),
        ),
    ]
