# Generated by Django 3.2.9 on 2021-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('space', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('statement', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('first_statement', models.TextField(blank=True)),
                ('typeOf', models.CharField(choices=[('String', 'String'), ('Array', 'Array'), ('Linked List', 'Linked List')], max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ManyToManyField(blank=True, to='basic.Company')),
                ('methods', models.ManyToManyField(blank=True, to='basic.Method')),
            ],
        ),
    ]
