# Generated by Django 3.2.9 on 2021-12-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_method', to='basic.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='questions_methods', to='basic.Method'),
        ),
    ]
