# Generated by Django 3.2.9 on 2021-12-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20211204_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
