# Generated by Django 3.2.9 on 2021-12-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_method_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='img1',
            new_name='algo',
        ),
        migrations.AddField(
            model_name='method',
            name='code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
