# Generated by Django 3.2.9 on 2021-12-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20211222_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='type',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
